### ISSUE TITLE
about LA dataset train

### ISSUE THREAD

**Issue by 15634354109** [HengCai-NJU/DeSCO#4]
Hello, you used the orthogonal annotation method in your paper. You only used two slices for each picture, but there are more than two slices reflected in the code. Is the code fake?
code: label[:, label.shape[1]//2, :] = truelabel[:, label.shape[1]//2, :]

**Comment by HengCai-NJU** [comment]
you might have misunderstood this line of code, 'label' here is the pseudo label generated by registration and the 'truelabel' is the dense ground truth label. label.shape[1]//2 is the annotated slice in coronal plane, and we just replace this slice in pseudo label with its ground truth annotation, (which is one of the two annotated slices).

**Comment by 15634354109** [comment]
> 你可能误解了这行代码，这里的“label”是注册生成的伪标签，“truelabel”是密集的地面真实标签。label.shape[1]//2 是冠状平面中带注释的切片，我们只需用其真实注释替换伪标签中的该切片（这是两个带注释的切片之一）。

Thank you for your answer, I understand.

**Comment by 15634354109** [comment]
> 你可能误解了这行代码，这里的“label”是注册生成的伪标签，“truelabel”是密集的地面真实标签。label.shape[1]//2 是冠状平面中带注释的切片，我们只需用其真实注释替换伪标签中的该切片（这是两个带注释的切片之一）。

你好，我想再问一下，在LA数据集上训练时，先要运行la_heart_processing.py，再运行registration.py，再去训练？
